apiVersion: v2
# renovate: datasource=github-releases depName=jacobalberty/unifi-docker
appVersion: v9.0.108
kubeVersion: ">=1.18-0"
description: Ubiquiti Network's Unifi Controller
name: unifi
version: 1.11.1
keywords:
  - ubiquiti
  - unifi
  - mongodb
home: https://github.com/mkilchhofer/unifi-chart
icon: https://blog.ubnt.com/wp-content/uploads/2016/10/unifi-app-logo.png
sources:
  - https://github.com/jacobalberty/unifi-docker
maintainers:
  - name: mkilchhofer
    url: https://github.com/mkilchhofer/
