apiVersion: v2
# renovate: datasource=github-releases depName=jacobalberty/unifi-docker
appVersion: v10.0.162
kubeVersion: ">=1.18-0"
description: Ubiquiti Network's Unifi Controller
name: unifi
version: 1.16.0
keywords:
  - ubiquiti
  - unifi
  - mongodb
home: https://github.com/mkilchhofer/unifi-chart
icon: https://prd-www-cdn.ubnt.com/static/favicon-152.png
sources:
  - https://github.com/jacobalberty/unifi-docker
maintainers:
  - name: mkilchhofer
    url: https://github.com/mkilchhofer/
